### ISSUE TITLE
Error While Go Getting

### ISSUE THREAD

**Issue by rschwass** [lair-framework/drone-nmap#3]
When I run:
# go get github.com/lair-framework/drone-nmap
I get:
src/github.com/lair-framework/drone-nmap/main.go:91: h.Os.OsMatch undefined (type nmap.Os has no field or method OsMatch)
src/github.com/lair-framework/drone-nmap/main.go:95: h.Os.OsMatch undefined (type nmap.Os has no field or method OsMatch)

**Comment by tomsteele** [comment]
Fixed, thanks for finding this.
