### ISSUE TITLE
[Bug] Running into issues pushing nmap results to lair

### ISSUE THREAD

**Issue by Cr0n1c** [lair-framework/drone-nmap#5]
I am probably doing something wrong. I have validated that 11013 and 11014 are open and all data is from a lab environment.

I have to use the -k option because if i don't i get the following error:
`root@kali:~/Downloads# drone-nmap friDNmAyY8Lh7vu3K ~/nmap_results/10.11.1.1.24.basic 
2016/12/15 14:05:20 Fatal: Unable to import project. Error x509: certificate is valid for , not localhost`

Configuration 
`root@kali:~/Downloads# uname -a
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
root@kali:~/Desktop# nmap -V
Nmap version 7.25BETA2 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.1 openssl-1.0.2h libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select`

Where it breaks
`root@kali:~/Downloads# export LAIR_API_SERVER='https://admin@localhost:mysupersecretpassword@localhost:11013'
root@kali:~/nmap_results# nmap -Pn -p20,21,22,23,25,80,110,123,135,139,443,445,3389 -oX 10.11.1.1.24.basic -v 10.11.1.1/24
root@kali:~/nmap_results# nmap -oX 10.11.1.1.24.basic2 -v 10.11.1.1/24
root@kali:~/Downloads# drone-nmap -k friDNmAyY8Lh7vu3 ~/nmap_results/10.11.1.1.24.basic 
2016/12/15 14:00:09 Fatal: Could not unmarshal JSON. Error invalid character 'B' after top-level value`

[10.11.1.1.24.basic.txt](https://github.com/lair-framework/drone-nmap/files/655569/10.11.1.1.24.basic.txt)

**Comment by jamesbcook** [comment]
Hello,

Please take a look at the following link https://github.com/lair-framework/lair/wiki/Common-Issues.

I was able to import the provided file with the latest drone.
